### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by davirs** [FrDH/mburger-css#2]
Hi! I am getting this error on my console ... What is it?
Thank you

SyntaxError: export declarations may only appear at top level of a module       mobile-burger.js:11

**Comment by FrDH** [comment]
It tells you the export declaration can only appear at the top level of a module :)
My guess is you're trying to use the webcomponent as if it were a plain javascript file. 

If you've followed [the tutorial](http://mmenujs.com/mburger/tutorial/webcomponent.html), please change this line:
````html
<script src="path/to/mburger.js"></script>
````
to
````html
<script src="path/to/mburger.js" type="module"></script>
````

(I'll make sure to update it shortly)

Or have a look at the demo page:
https://github.com/FrDH/mburger-css/blob/master/index.html#L15

Hope this helps.
