### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by Anke** [FrDH/mburger-css#3]
Hi,

I implemented mburger together with mmenu. It seems to be working when the hamburger icon is wrapped in an a-tag as described in your online documentation. Replacing it by button-tags like in your downloaded example page, it doens't react.

Either way the console reports: 
`SyntaxError: export declarations may only appear at top level of a module - mburger.js:11`

Line 11 says: 
`export const mBurger = document.createElement('template');`

I don't know what this error means or what might be causing it, because it doesn't appear on another website.

**Comment by FrDH** [comment]
Be sure to include the .js script in a `type="module"` script tag:
````html
<script type="module" src="dist/mburger.js"></script>
````
Otherwise I can't think of any reason for that syntaxerror.

**Comment by Anke** [comment]
Thank you - that did it. (Sorry, didn't even know there was a module script type.)
