### ISSUE TITLE
Usage with mmenu light

### ISSUE THREAD

**Issue by fluxxus** [FrDH/mburger-css#4]
Is it possible to use `mburgers` with lighter version of `mmenu` ?

**Comment by FrDH** [comment]
Yes, but you'll need to write some JS.

Clicking the hamburger to open the menu is explained in the mmenu light tutorial.
The hamburger turns into a cross when it is inside an element with `class=".mm-wrapper_opened"`.

**Comment by fluxxus** [comment]
Ok, thanks. I just wanted to make sure it is possible.
